# Generated by Django 3.2 on 2022-04-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscribe',
            new_name='Subscriptions',
        ),
    ]
